FROM ruby:3.1.2
RUN apt-get update
RUN apt-get install -y build-essential nodejs
RUN mkdir -p /app
WORKDIR /app
COPY ./backend/ .
RUN gem install bundler -v '2.3.17' && bundle install --jobs 20 --retry 5
RUN rm -rf *
EXPOSE 3000

